### ISSUE TITLE
Delay state

### ISSUE THREAD

**Issue by lupinve** [h4de5/home-assistant-vimar#12]
Hi,

I recently purchased a Vimar 01946 web server and easily managed to use your project with home assistant version 0.112.3 on Raspberry 4. Lights and thermostats were detected.  For thermostats I have yet to try to test them.  For the lights I have a lag problem when I turn the light on or off from the Vimar device.  The state on HA has a delay of approximately 30 seconds.  Is it a known problem or a configuration problem of my system?

 Thanks for your help 
Matteo

**Comment by h4de5** [comment]
Yes unfortunately this is known. I have to delay the update requests from home-assistant to the webserver, otherwise the webserver goes into an unresponsive state and requires a cold restart.

**Comment by lupinve** [comment]
I currently have version 2.3 of the webserver. I'd like to try to change the delay of update requests. I can try testing if you tell me where I can change the delay.
Thanks
Matteo

**Comment by h4de5** [comment]
in each platform (light.py, cover.py, switch.py, climate.py) you will find two consts:

```
SCAN_INTERVAL = timedelta(seconds=20)
PARALLEL_UPDATES = 2
```

see: https://github.com/h4de5/home-assistant-vimar/blob/957b4bf4e1ebbc780382034884290eb330b813f1/light.py#L20

the first one is the time for how long each entity waits until it polls the webserver for new data. the second defines how may parallel requests can run at the same time. 

you can play around with those numbers - but be informed, that the webserver may become unresponsive. i havn't got time to test out the limits as I am trying to fix this issue using a different approach.

**Comment by lupinve** [comment]
Hi,

I'm still testing the delay and for now it seems to work well with this setting, only for light.py:

SCAN_INTERVAL = timedelta(seconds=6)
# MIN_TIME_BETWEEN_UPDATES = timedelta(seconds=3)
PARALLEL_UPDATES = 3

I also wanted to ask you if Vimar's IR sensor integration is already possible. In my xml it is detected but in HA it is considered light and does not work properly.

<index index="120" label="SENSORE IR SALOTTO " number="0" room="SALOTTO" type="SENSORE IR" zone="">
        <datapointtypes channel="CH_Main_Automation">
          <datapointtype mode="rw" name="DPTSwitch">
            <groupobject address="0EF9"/>
          </datapointtype>
        </datapointtypes>
        <device address="1108" manufacturer="002C" name="ConvimarSAISensoreIR" type="0001" version="8">
          <properties/>
          <functionalblock channel="CH_Main_Automation" classification="sensor" index="2" main="True" name="ConvimarSensoreIR">
            <groupobjects>
              <datapointtype mode="rw" name="DPTSwitch"/>
            </groupobjects>
            <properties/>
          </functionalblock>
        </device>
      </index>

Do I have to change any data?
Thanks so much !!!!!

**Comment by h4de5** [comment]
I see. An IR sensor would be like a switch or like a sensor (without the possibility to change its state from ha?)

**Comment by lupinve** [comment]
like a switch
https://www.vimar.com/en/int/catalog/product/index/code/20485
i can use it for turn on the light when people show up 

at the moment it is detected as a light that once activated does not turn off anymore

**Comment by h4de5** [comment]
Ah i see. Maybe setting its state simply to 1 is wrong for that device. Can you have a look at contributing.md (the second part about setting a value) ?

**Comment by lupinve** [comment]
i try it, there seems to be no movement variation
i find this value

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-databasesocketoperation xmlns="urn:xmethods-dpadws"><payload>NO-PAYLOAD</payload><hashcode>NO-HASCHODE</hashcode><optionals>NO-OPTIONAL</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f1328dbf1e3e</sessionid><waittime>5</waittime><function>DML-SQL</function><type>SELECT</type><statement>SELECT ID,NAME,STATUS_ID,CURRENT_VALUE FROM DPADD_OBJECT WHERE ID IN (229,265,598);</statement><statement-len>83</statement-len></service-databasesocketoperation></soapenv:Body></soapenv:Envelope>

ns:service-databasesocketoperationResponse
>
<result-len
>
Response payload length: 303
</result-len
>
<result
>
DPCM-0000
</result
>
<payload-len
>
303
</payload-len
>
<payload
>
Response: DBMG-000
NextRows: 4
Row000001: 'ID','NAME','STATUS_ID','CURRENT_VALUE'
Row000002: '229','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_VIDEOMESSAGE_UNHANDLED','-1','0'
Row000003: '265','_DPAD_DBCONSTANT_VIMAR_BYME_TRIGGEROBJECT_SENSORS_HUMIDITY_ALARM','-1','0'
Row000004: '598','on/off','-1','1'

**Comment by h4de5** [comment]
this seems to be the read state - no the set state. I would need to request/payload that is sent to the webserver- not the answer.
but I guess - as this still does only have a normal on/off state, the timer is somehow realized differently.
You could have those timers within ha automations like this:

```yaml
"some_uniqe_name":
  alias: büro rollos öffnen
  sequence:
    - data: {}
      entity_id:
        - light.id_of_light1
        - light.id_of_light2
      service: light.turn_on
    - delay: 0:00:15
    - data: {}
      entity_id:
        - light.id_of_light1
        - light.id_of_light2
      service: light.turn_off
```

this is just a script (for script.yaml) that will turn off those given lights after 15sec. you could play around with automations.

**Comment by h4de5** [comment]
@lupinve with the latest code push, the updates should be comming in much faster. the entity states will be updated once every 6 seconds. 

I am closing this issue as the original issue seems to be working already. Please let me know if that's not the case.

switching lights off after a given time, needs to be added through hass automations, i guess. also let me know if you made progress there.

**Comment by lupinve** [comment]
hi, i'm testing again Vimar IR sensor for check presence of someone on the room.

at the moment it is not working correctly because once the sensor is detected the presence of someone is always on

i have found this playod when i try of on/off the sensor:

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-databasesocketoperation xmlns="urn:xmethods-dpadws"><payload>NO-PAYLOAD</payload><hashcode>NO-HASCHODE</hashcode><optionals>NO-OPTIONAL</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>5</waittime><function>DML-SQL</function><type>SELECT</type><statement>SELECT ID,NAME,STATUS_ID,CURRENT_VALUE FROM DPADD_OBJECT WHERE ID IN (229,265,399,595,1106);</statement><statement-len>92</statement-len></service-databasesocketoperation></soapenv:Body></soapenv:Envelope>	
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-runonelement xmlns="urn:xmethods-dpadws"><payload>1</payload><hashcode>NO-HASHCODE</hashcode><optionals>NO-OPTIONALS</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>10</waittime><idobject>595</idobject><operation>SETVALUE</operation></service-runonelement></soapenv:Body></soapenv:Envelope>
`ON`
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-databasesocketoperation xmlns="urn:xmethods-dpadws"><payload>NO-PAYLOAD</payload><hashcode>NO-HASCHODE</hashcode><optionals>NO-OPTIONAL</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>5</waittime><function>DML-SQL</function><type>SELECT</type><statement>SELECT ID,NAME,STATUS_ID,CURRENT_VALUE FROM DPADD_OBJECT WHERE ID IN (229,265,399,1106);</statement><statement-len>88</statement-len></service-databasesocketoperation></soapenv:Body></soapenv:Envelope>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-runonelement xmlns="urn:xmethods-dpadws"><payload>0</payload><hashcode>NO-HASHCODE</hashcode><optionals>NO-OPTIONALS</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>10</waittime><idobject>595</idobject><operation>SETVALUE</operation></service-runonelement></soapenv:Body></soapenv:Envelope>
OFF
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-databasesocketoperation xmlns="urn:xmethods-dpadws"><payload>NO-PAYLOAD</payload><hashcode>NO-HASCHODE</hashcode><optionals>NO-OPTIONAL</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>5</waittime><function>DML-SQL</function><type>SELECT</type><statement>SELECT ID,NAME,STATUS_ID,CURRENT_VALUE FROM DPADD_OBJECT WHERE ID IN (229,265,399,1106);</statement><statement-len>88</statement-len></service-databasesocketoperation></soapenv:Body></soapenv:Envelope>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-runonelement xmlns="urn:xmethods-dpadws"><payload>1</payload><hashcode>NO-HASHCODE</hashcode><optionals>NO-OPTIONALS</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>10</waittime><idobject>595</idobject><operation>SETVALUE</operation></service-runonelement></soapenv:Body></soapenv:Envelope>
ON
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><service-databasesocketoperation xmlns="urn:xmethods-dpadws"><payload>NO-PAYLOAD</payload><hashcode>NO-HASCHODE</hashcode><optionals>NO-OPTIONAL</optionals><callsource>WEB-DOMUSPAD_SOAP</callsource><sessionid>5f82f98d8a3ca</sessionid><waittime>5</waittime><function>DML-SQL</function><type>SELECT</type><statement>SELECT ID,NAME,STATUS_ID,CURRENT_VALUE FROM DPADD_OBJECT WHERE ID IN (229,265,399,595,1106);</statement><statement-len>92</statement-len></service-databasesocketoperation></soapenv:Body></soapenv:Envelope>

Thanks for your help
Matteo
