### ISSUE TITLE
[SETUP] Please help with my setup

### ISSUE THREAD

**Issue by srodighiero** [h4de5/home-assistant-vimar#21]
**Describe the problem**

**Check for some things first**

- [x] the source code of the integration is cloned into the right directory: `config/custom_components/vimar_platform`
- [x] the `config/` directory above (can be named differently) but it should hold the general `configuration.yaml` and the `home-assistant.log` file
- [x] the tips listed under [troubleshooting](https://github.com/h4de5/home-assistant-vimar#troubleshooting) did not help me with my issue.
- [x] I updated to the most recent version of this integration
- [x] I checked existing issues, that may have the same issue

**Setup**

 - Environment: [e.g. raspberryPi, macos, virtualenv, docker]
 - Home-Assistant Version: [e.g. v0.110.3]
 - By-me web server Version: [e.g. v1.25]

**Screenshots**

**Additional context**

Virtualenv in mac catalina, webserver vimar 01946 firmware 2.8 (Rev. 24952), ha 0.117.5
Worked after first installation, needed to put certificate in place because script is unable to download it (keeps saying file not found even if url/path correct) but when restarting hass this is the log:

Logger: homeassistant.setup
Source: custom_components/vimar_platform/__init__.py:205
First occurred: 22:40:16 (1 occurrences)
Last logged: 22:40:16

Error during setup of component vimar_platform
Traceback (most recent call last):
  File "/Users/stefy/homeassistant/lib/python3.8/site-packages/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/Users/stefy/.homeassistant/custom_components/vimar_platform/__init__.py", line 91, in async_setup
    vimarproject, vimarconnection = await _validate_vimar_credentials(hass, vimarconfig)
  File "/Users/stefy/.homeassistant/custom_components/vimar_platform/__init__.py", line 205, in _validate_vimar_credentials
    raise PlatformNotReady
homeassistant.exceptions.PlatformNotReady

**Comment by B3rts** [comment]
I have the same problem.

**Comment by B3rts** [comment]
OK, I solved it by manually copying the certificate to the "config" folder.

**Comment by srodighiero** [comment]
manually copying the certificate to the "config" folder for me did not work, but was solved by leaving blank/empty the value for "ceritifcate" on configuration.yaml
