### ISSUE TITLE
[FEATURE] Map only some element categories.

### ISSUE THREAD

**Issue by lollo03** [h4de5/home-assistant-vimar#24]
A lot of people use KNX/IP interfaces on vimar installations. I think you should add a configuration that only enables some categories of elements. Example: I want to import only the climate control using the integration because I have all my light on a different integration. It should be easy to add and pretty useful!.

**Comment by h4de5** [comment]
@lollo03 see example config: https://github.com/h4de5/home-assistant-vimar#ignore-platforms

**Comment by lollo03** [comment]
Thank you very much
