### ISSUE TITLE
without home-assistant

### ISSUE THREAD

**Issue by AuZ-ASD** [h4de5/home-assistant-vimar#28]
Hi h4de5!
sorry for abusing the issue to contact you - cant find any other way.

i'm also one of the vimar customers. we got the system with our new house nearly 10 years ago
i also have the webserver some realy old version i guess as the local supportcompany was already scared to update it long time ago so this is still running ~8year old softwre :)

im contacting you as i found your tool for home-assistant... im not using homeassistant but im searching for some tool that can connect to the webserver and do basic tasks like switching lights on/off or up/down the shades. 
for me it would be great if i simply can run this via some easy commandlin within my linux box so i can easy swich on the light by crontab for example instead of using the (crappy) builtin schedulers.

I would like to hear from you, also if you are not able to help me - but if you can I would also be willing to pay... tell me what you thing and we can see if we come together.

greetings also from austia, Wien 16. :)

**Comment by h4de5** [comment]
seas ;)

basically you just need the `vimarlink.py` which handles authentification, data geters and seters.

everything else around is for home-assistant and implements a basic usage of that class.

my plan was/is to release that file on pypi along with examples code, once it reaches some kind of readyness. unfortunately i can't give you a timeframe for that.

but have a look at it, and see how far you can get ;)

**Comment by AuZ-ASD** [comment]
Hi,

thanks for your reply!
I don't know any programming stuff or can read the code..
if i look at the content of vimarlink.py ist like spanish to me :)

some example code would maybe help to recreate stuff and make it work.
let me know if you need some tester for this! 

Regards
ASD

**Comment by h4de5** [comment]
@AuZ-ASD  please have a look at the examples here: https://github.com/h4de5/home-assistant-vimar#command-line-usage
