### ISSUE TITLE
[SETUP] Please help with my "Command line usage" setup

### ISSUE THREAD

**Issue by AuZ-ASD** [h4de5/home-assistant-vimar#32]
Thanks for not forgetting about the simple CLI request!!!

today i tried it out but got error with the example.py 

error:

> root@host:/opt/home-assistant-vimar-master/examples# python3.9 example.py
> Error occurred: HTTPSConnectionPool(host='192.168.1.1', port=443): Max retries exceeded with url: /vimarbyweb/modules/system/user_login.php?sessionid=&username=myvimaruser&password=mysecretpassword&remember=0&op=login (Caused by SSLError(SSLError(0, 'unknown error (_ssl.c:4267)')))
> Error parsing XML: a bytes-like object is required, not 'bool'
> Login Exception: VimarConnectionError: Error parsing login response: Login failed - check username, password and certificate path - False
> Login failed
> 

**Setup**
- debian 9
- Python 3.9.4 (installed via https://tecadmin.net/how-to-install-python-3-9-on-debian-9/ )
- By-me web server Version: [e.g. v1.11 Rev. 16810]

I checked if i can download the certificate from the by-me webserver but the "network" section does not offer this... looks like this stoneold version does not offer this

**Comment by h4de5** [comment]
check if you can download the certificate frome here: https://your-vimar-webservers-ip/vimarbyweb/modules/vimar-byme/script/rootCA.VIMAR.crt

using a normal browser.
if this does not work, i am afraid you are right and your firmware version may be too old. if you consider upgrading, please be aware to make a full backup of your installation (xml and from easytool professional).

**Comment by AuZ-ASD** [comment]
Hi!
looks like my version is to old... i disabled the cert by simply setting 
`certificate = ''`
also removed the warnings with 
```
import urllib3
urllib3.disable_warnings()

```
so far it works great.. i can now simply swith on/off my lights
