### ISSUE TITLE
Upgrade Description not working

### ISSUE THREAD

**Issue by dennisschumann** [h4de5/home-assistant-vimar#35]
Hello,

I try to update from vimar_plattform to vimar integration using your guide, but I'm struggling with this step:

- find and backup the file: .storage/core.entity_registry within your home-assistant config directory

There is no such file (btw: im using Maria DB). There is only a 1 Gig file called home-assistant_v2.db. Any suggestions?

Best regards!

**Comment by h4de5** [comment]
hi, i think the .db file is only used for the history

**Comment by dennisschumann** [comment]
Thank you, I've re-configured HA.
