### ISSUE TITLE
Not working after uploading HA core

### ISSUE THREAD

**Issue by Niki206cc** [h4de5/home-assistant-vimar#36]
Good evening, the code was working perfectly (lights, thermostats, windows, etc) till i updated the core of HA.
Previously i had 2021.5.4 core and i updated to 2021.6.6, after rebooting the raspberry i have this error:

The following integrations and platforms could not be set up:
    vimar_platform

In the log i have:
Setup failed for vimar_platform: Integration not found.
18:33:33 – (ERRORE) setup.py

To let it work before i create the folder /custom_components/vimar_platform where i upload all the files.

I'm a newbie of HA, can you pls help me to solve the problem?
Thanks

**Comment by h4de5** [comment]
config key and custom_components directory was renamed to vimar (removing the _platform) if you use the latest version

**Comment by Niki206cc** [comment]
i already renamed the folder vimar_platform in vimar inside custom_components, i already replaced inside configuration.yaml
vimar:
  username: *****
  password: *****
  host: 192.168.1.110
  certificate:

i cannot find the file: .storage/core.entity_registry.
So to be sure i restored as before and now i have:
custom_components/vimar_platform
custom_components/vimar (where i uploaded all new files from github

and inside  configuration.yaml iui have
vimar:
  username: *****
  password: *****
  host: 192.168.1.110
  certificate:
but still not working...

**Comment by Niki206cc** [comment]
I found the file  .storage/core.entity_registry (it was hidden), i replaced all the vimar_platform text to vimar and....IT WORKS!!!!
Thanks again!!

**Comment by h4de5** [comment]
let me know if there are other issues.
