### ISSUE TITLE
[SETUP] Please help with my setup

### ISSUE THREAD

**Issue by Luke1964MI** [h4de5/home-assistant-vimar#37]
Ciao a tutti,
sono appena entrato nella grande community di HomeAssistant e subito mi si pone un problema nell'integrazione VIMAR:
se creo delle automazioni in  HA non si attivano gli scenari impostati nella domotica VIMAR (se lo comando con l'interfccia entità funziona tutto regolarmente)...
qualcuno mi può aiutare?

Hello everybody,
I have just joined the large HomeAssistant community and immediately a problem arises in the VIMAR integration:
if I create automations in HA, the scenarios set in the VIMAR home automation system are not activated (if I control it with the entity interface, everything works regularly) ...
Can anyone help me?

- Environment: macchina virtuale (8GBRAM) su pc WINDOWS10 - intel I3 - 12GBRAM
- Home-Assistant Version: 2021.7.3
- By-me web server Version: [versione 2.9

**Comment by h4de5** [comment]
can you post your HA automations script?

**Comment by Luke1964MI** [comment]
alias: Accendi le luci del giardino quando Luca arriva di notte
  description: ''
  trigger:
  - platform: device
    device_id: 
    domain: device_tracker
    entity_id: 
    type: enters
    zone: zone.home
  condition:
  - condition: sun
    after: sunset
    before: sunrise
  action:
  - scene: scene.in_on_luci
  mode: single

**Comment by Luke1964MI** [comment]
vimar:
  username: *******
  password: **************
  host: *****************
  certificate: rootCA.VIMAR.crt
  ignore:
    - climate
    - sensor
    - media_player

**Comment by Luke1964MI** [comment]
need anything else?
thank you so much for your help

**Comment by srodighiero** [comment]
Ciao Luke,

the original Vimar scenes when imported in HA they cannot be recalled directly with a button, for example, on lovelace dashboard, and they need to be recalled via a script. So my suggestion is to create a script for each scene, that recall the single scene, and use the script rather than the vimar scene in the automation, or even better create new scenarios inside HA and discard Vimar scenes

**Comment by Luke1964MI** [comment]
Thank you very much .... I tried your solution, now everything works.
I use VIMAR scenes only for some things and I have created the scenes and automations that interest me to operate directly on the entities.
