### ISSUE TITLE
[SETUP] Please help with my setup

### ISSUE THREAD

**Issue by felisida** [h4de5/home-assistant-vimar#41]
**Describe the problem**

Hi I had to reinstall home assitant from a backup, it was not the first time this happened to me, but now it no longer recognises the vimar components, I tried rebooting several times, but nothing. it seems that the problem is in the certificate but I don't understand it has always worked

**Setup**
- Environment: Proxmox - supervisor
- Home-Assistant Version: core-2021.11.5
- By-me web server Version: 2.10
**Screenshots**

![Schermata 2021-12-04 alle 13 12 43](https://user-images.githubusercontent.com/51525150/144708968-001faa4a-7967-4fc3-b25a-6a55bb421e2b.jpg)

![Schermata 2021-12-04 alle 13 12 07](https://user-images.githubusercontent.com/51525150/144708970-b609863f-14d6-46ff-9449-29b58e993735.jpg)
![Schermata 2021-12-04 alle 13 11 47](https://user-images.githubusercontent.com/51525150/144708978-85dfa333-8f36-4e4c-818f-5d204e568581.jpg)

**Comment by felisida** [comment]
After an update of the firmware of the vimar webserver everything went back to normal.

**Comment by h4de5** [comment]
i had the same fight 2 days ago. i think the problem was that the integration had stored a previous version of the certificate in the HA config folder. and the vimar web server created a new one. 
in my case I just had to delete the old certifcate and restart HA.
glad to hear that you found a way to fix it!

**Comment by felisida** [comment]
Yes, thanks for you reply

Saluti Felice
Il 5 dic 2021, 01:07 +0100, Andi ***@***.***>, ha scritto:
