### ISSUE TITLE
Config Flow: Implementation of Config Flow | Thread/Discussion & Documentation

### ISSUE THREAD

**Issue by robigan** [h4de5/home-assistant-vimar#46]
Hello World, summer holidays have started for me, and I've decided to work on implementing the config_flow.py into the vimar custom component.

Why does this issue exist? This issue exists to discuss the way config_flow.py should be implemented and to document any interesting findings along the way.
Where's the work on this feature? The work on this feature can be found on [my fork of the repo](https://github.com/robigan/home-assistant-vimar/tree/feature/config_flow)

**Comment by h4de5** [comment]
to make sure that there are options for users who do not want to change things, is part of the testing.

**Comment by h4de5** [comment]
closed via #48
