### ISSUE TITLE
entities offline after the update of by-me integration

### ISSUE THREAD

**Issue by felisida** [h4de5/home-assistant-vimar#49]
Hi Andy,
this morning after doing the update from HACS of the By me integration, all entities are not available
this is my installation running on proxmo
![Schermata 2022-07-29 alle 11 20 21](https://user-images.githubusercontent.com/51525150/181728500-b237dab1-2faf-44fe-b1a1-e061c9df3a8d.jpg)
x

**Comment by h4de5** [comment]
the latest update includes moving from the traditional configuration via config file, to the config flow using the integration page.

see if you can find it from there:

![image](https://user-images.githubusercontent.com/6115324/181834219-8aa30065-e839-4449-ab43-d700e9a5b8d3.png)
![image](https://user-images.githubusercontent.com/6115324/181834190-c409a70f-ac53-4c8e-8397-38787a48c54e.png)
![image](https://user-images.githubusercontent.com/6115324/181834384-0a640253-c465-410e-86bd-d6ddf58ed40c.png)
![image](https://user-images.githubusercontent.com/6115324/181834107-2bb3e597-a6f3-49f0-aa32-11994020b1e8.png)

the config flow also asks you if you want to rename your entities - keep those checkboxes off to keep your exsiting naming.

**Comment by felisida** [comment]
hi, I followed your instructions, but the results is the same all entities ar off-line, tried too to activate ssl, because my istance of ha work with ssl

**Comment by melaqu** [comment]
Same issue. I have a question: do I have to delete Vimar info in configuration.yaml?

**Comment by felisida** [comment]
I tried to delete  info from configuration.yaml, but without success

**Comment by davideciarmiello** [comment]
Hi. @felisida  can you check if you have a logs with errors? 
The config flow, completed with success? 
in page of integrations, on Vimar integration, are listed a devices?

**Comment by h4de5** [comment]
it should not be necessary to remove the vimar entry from configuration.yaml - on the other hand it should be necessary to have it in the future.

some tests showed, that ab existing vimar connection was not reused - but instead a new one was created. This resulted in duplicated entities - you would see something like light.first_floor_bath_1 and light.first_floor_bath_1_2, one offline and one connected but not used in any dashboard.

to get around this, here is what I did:
* i did a backup of the whole HA installation (specially the database and the device entries) !
* remove the "vimar:" config entry from configuration.yaml, and if already present, remove the vimar config flow entry as well.
* restart HA
* go to [entites](https://ha.pauschenwein.net/config/entities) search for all "vimar" and remove them all (make sure to only check those which are coming from "VIMAR by-me Hub" integration)
* maybe restart HA again to make sure that there is nothing left
* then go to integrations, search for Vimar and add the integration again from scratch - see pictures above

i tried this a couple of times to make sure, that the entity_ids stays the same as they where before the upgrade to config flow. so any automations that are build based on those ids still work. But: If you follow this way, the entity name (friendly name) and manually selected icons will be reset to what Vimar returns.

**Comment by felisida** [comment]
Perfect now all is ok.
thanks a lot
