### ISSUE TITLE
Support of By-me gateway 01411

### ISSUE THREAD

**Issue by hansinz** [h4de5/home-assistant-vimar#50]
I understand that the gateway 01411 is not supported by this integration. According to information from Vimar, this gateway can be connected directly in the local network. Would you prefer, if an integration of this gateway is added into this integration. Or do you think a new Home Assistant integration for this gateway would be better?

**Comment by h4de5** [comment]
I would not know how to connect to the gateway. what you can do is, take this integration as an example for a first prototype and once you get something working, we can have a look if merging into one integration is feasible.

best regards
