### ISSUE TITLE
Regex for set entities as binary_sensor

### ISSUE THREAD

**Issue by lupinve** [h4de5/home-assistant-vimar#53]
Hi,

thanks for your great job !!!

i don't know as set the Regex number for my  iR Sensor listed as a normal light switch currently in HA

i have this value
![entities](https://user-images.githubusercontent.com/61914003/197348581-c5b1f2c0-444f-4d95-b4a1-43f3791d020e.PNG)

which number i have to set in RegEx for set entities switch as bynary_sensor ?

If i have a lot ot this ir sensor, can i set more number  ? 

![RegEx](https://user-images.githubusercontent.com/61914003/197348745-e71d2c01-24d9-4239-9280-e6c58da1c733.PNG)

**Comment by h4de5** [comment]
@davideciarmiello would this work using the regex options?

**Comment by davideciarmiello** [comment]
Hi. Yes it work with regex.
Attach my config 
![E1236037-1FD0-4B59-A395-FDFFCB9147B2](https://user-images.githubusercontent.com/18262360/197364799-8e4162ab-32cb-4196-bb86-77bd7c5ec2a8.jpeg)

the match is executed on friendly name. In my config i have checked “use naming as vimar”, that use object name as friendly name.

you can try:
 .*(Ir.*Sensore|sensore ir).*
 
Thanks!

**Comment by h4de5** [comment]
@lupinve have you tried this? if its not working let us know.

**Comment by lupinve** [comment]
Hi Andi,

I'm sorry for the late reply....

Thanks for your help !!!!

yes it's work fine but the vimar ir sensor can't change the state from off
to on  so i have to back to light mode




Il giorno dom 20 nov 2022 alle ore 02:56 Andi ***@***.***> ha
scritto:
