### ISSUE TITLE
Publish sessionid

### ISSUE THREAD

**Issue by WhiteWolf84** [h4de5/home-assistant-vimar#67]
Hi,

can you publish the connection sessionid like an attribute of the vimar connection entity?

I'm searching to use the restful integration to make SAI Alarm simple actions to integrate in scripts but dealing with sessionid creation is a nightmare.

Thanks!

**Comment by WhiteWolf84** [comment]
Hi,

I've managed to expose the sessionID, it was almost already there, I've added a single row...

but with my experiments I've managed to retrieve the WSDL of the SOAP interface.

You can download it via https://[yourserverIP]/html/dpadws.wsdl

BTW I've managed to activate and deactivate alarm, but nothing more. Sadly the status of sensors nad areas isn't in a REST JSON format... :-(

**Comment by WhiteWolf84** [comment]
Hi,

I'm not a coding expert and I've never used tools like github.... but I've tried to contribute... #68

**Comment by h4de5** [comment]
very good so far - I have merged it and will add it in the next release. :)
thank you very much for your contribution - I hope you can still find a way to integrate SAI alarms.
