### ISSUE TITLE
Problems with Vimar web Server 1.7

### ISSUE THREAD

**Issue by stefben81** [h4de5/home-assistant-vimar#75]
Dear Sirs,
i try to install and connect to my (very old) web server (firmware version 1.7) and each time the software says: "Invalid certificate, try change or remove"
I think that is because the SSL implementation in VIMAR is without certificate. 
Other people have seen this type of problem? Any ideas?

**Comment by marcogeni** [comment]
Hi stefben81, did you try to download the CA certificate from the setup page of the Vimar By-me server?

**Comment by h4de5** [comment]
i think at some point it was no longer possible to create an browser exception for the old vimar certificate. because sslv3 (or some cipher) was considered unsecure.

iirc the only option was to upgrade the vimqr webserver firmware. current version is 2.11. keep in mind to create backups before you do this and maybe get the contacts from your installer ready.

**Comment by stefben81** [comment]
> Hi stefben81, did you try to download the CA certificate from the setup page of the Vimar By-me server?

Thank you for the answer. Is seem that the CA certificate is not present in this version of web server

**Comment by stefben81** [comment]
> i think at some point it was no longer possible to create an browser exception for the old vimar certificate. because sslv3 (or some cipher) was considered unsecure.
> 
> iirc the only option was to upgrade the vimqr webserver firmware. current version is 2.11. keep in mind to create backups before you do this and maybe get the contacts from your installer ready.

Correct, but i have contact Vimar and they says that i can't upgrade the firmware for my web server. I have the Hardware version 00 and they do not garantee that the update can be do. Maybe that web server freeze, for this reason I do not want upgrade the firmware
