### ISSUE TITLE
[ISSUE] problems with HA 2024.4.1

### ISSUE THREAD

**Issue by WhiteWolf84** [h4de5/home-assistant-vimar#76]
After updating HA to 2024.4.1 I receive this error:
L'integrazione personalizzata vimar implementa la proprietà is_aux_heat o utilizza i metodi del riscaldatore ausiliario in una sottoclasse di ClimateEntity.

![immagine](https://github.com/h4de5/home-assistant-vimar/assets/93442510/5c5057de-907b-4fd1-8fec-d851d7eab9b9)

**Comment by robigan** [comment]
Semplicemente funzionerà ma a partire da 2024.10.0 non funzionerà la versione del plugin che hai installato, eventualmente ci sarà un aggiornamento

**Comment by FabianNiesen** [comment]
Any news on this topic? I have the lattest release, but I have seen, that there was a commit (eeb7374) for the "first fixes" regard this topic 5 month ago. Will there be a new release in time?

**Comment by robigan** [comment]
> Any news on this topic? I have the lattest release, but I have seen, that there was a commit ([eeb7374](https://github.com/h4de5/home-assistant-vimar/commit/eeb7374ffadcea5b2356618b8bd0dbe2433979e7)) for the "first fixes" regard this topic 5 month ago. Will there be a new release in time?

Not sure, I sure do hope. I am currently busy with school work, otherwise I'd implement the fixes myself

**Comment by h4de5** [comment]
please update to latest version.
