### ISSUE TITLE
Will this work with their doorbell video system? 

### ISSUE THREAD

**Issue by HobbySynergy** [h4de5/home-assistant-vimar#77]
I have both HA yellow and Hubitat installed, I am trying to somehow see who's at the gate, open the gates all using HomeKit in the end. 
the device is connected by wifi(inside the house).

Any way to make it work with HA/HE?

Thank you

**Comment by h4de5** [comment]
i do not know hubitat. this integration is only about the vimar bus system - which on their own do not have doorbells or video systems.
