### ISSUE TITLE
[FEATURE] New Gateway 011411

### ISSUE THREAD

**Issue by felisida** [h4de5/home-assistant-vimar#79]
due to a problem with the alarm Gateway I had to replace the old Gateway with the new one the 01411. I thought it was not a problem for HA as it is stated to be compatible with HomeKit, but out of the whole system it only sees the lights, actually it also sees the thermostats but not correctly and they are not manageable. I tried to call support but they say it must be apple that has to fix HomeKit; now I was wondering if I gave you cloud access do you think it is possible to create a new integration for HA?
of course I can season you with credentials to operate on my system, also on FaceBook I found someone who has done something and is looking for a programmer. if you are interested let me know 
the name of user is [Thomas Feregotto] and Wrote: "On the topic VIMAR BY-ME plus communication with new ip gateways 01411. With nodered I was able to connect via websocket, perform the pairing step with the gateway using certificates, I was able to control a device and register on it to receive status. Looking for python developers interested in collaborating to do a Homeassistant integration - vimar by-me plus"

Saluti Felice

**Comment by h4de5** [comment]
see #50 #40
