### ISSUE TITLE
Upgrade plugin to fix deprecations

### ISSUE THREAD

**Issue by robigan** [h4de5/home-assistant-vimar#80]
### IF YOU HAVE COME HERE BECAUSE OF THE `is_aux_heat` WARNING, UPDATING TO 2024.10 MIGHT CAUSE THE PLUGIN TO STOP WORKING

Things to fix:
`vimar::VimarClimate implements the is_aux_heat property or uses the auxiliary heater methods in a subclass of ClimateEntity which is deprecated and will be unsupported from Home Assistant 2024.10. Please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues`
Deprecation in a few days (until October release comes out)

<hr>

`Entity None (<class 'custom_components.vimar.climate.VimarClimate'>) implements HVACMode(s): heat, cool, off, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues`
I presume this is from new versions requiring some new class properties to be set

<hr>

`Entity None (<class 'custom_components.vimar.climate.VimarClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE|AUX_HEAT: 73>, please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`

`STATE_CLASS_TOTAL_INCREASING was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.TOTAL_INCREASING instead, please report it to the author of the 'vimar' custom integration`

`STATE_CLASS_MEASUREMENT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorStateClass.MEASUREMENT instead, please report it to the author of the 'vimar' custom integration`

`ELECTRIC_POTENTIAL_VOLT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricPotential.VOLT instead, please report it to the author of the 'vimar' custom integration`

`HVAC_MODE_HEAT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'vimar' custom integration`

`HVAC_MODE_OFF was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_AUX_HEAT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.AUX_HEAT instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_FAN_MODE was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_TARGET_TEMPERATURE was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_OPEN_TILT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.OPEN_TILT instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_SET_POSITION was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_POSITION instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_SET_TILT_POSITION was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.SET_TILT_POSITION instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_STOP was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP instead, please report it to the author of the 'vimar' custom integration`

`SUPPORT_STOP_TILT was used from vimar, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverEntityFeature.STOP_TILT instead, please report it to the author of the 'vimar' custom integration`

`Entity None (<class 'custom_components.vimar.light.VimarLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation`
Deprecation in January 2025

<hr>

`None (<class 'custom_components.vimar.light.VimarLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues`
Deprecation in March 2025

<hr>

`Detected code that calls async_forward_entry_setup for integration, vimar with title: Home and entry_id: 4c401aeb90d7754b66423c731a4a1c9d, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead. Please report this issue.`
Deprecation in May 2025

<hr>

`Detected that custom integration 'vimar' accesses hass.helpers.service. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from service directly at custom_components/vimar/__init__.py, line 178: hass.helpers.service.async_register_admin_service(, please create a bug report at https://github.com/h4de5/home-assistant-vimar/issues`
Deprecation in November (1 month)

<hr>

Some stuff to fix ngl

cc @h4de5
I'd try to fix this myself, but I am currently busy with school work

**Comment by WhiteWolf84** [comment]
Hi, I'm not able to develop a solution but I can help with testing, if you want.

**Comment by tempod** [comment]
this project still alive?

**Comment by robigan** [comment]
> this project still alive?

Probably is, but @h4de5 only pops on a few months a year
