### ISSUE TITLE
Crash on 2024.10.1

### ISSUE THREAD

**Issue by alanmastro** [h4de5/home-assistant-vimar#82]
after updating to version 2024.10 and later 2024.10.1, keeping the extension active after a few minutes Home Assistant crashes saturating the CPU. I don't know if the problem is related to another issue #80 but I tried to apply the patch of the associated  (#81) pull request, but without success. in practice, at present, it is unusable with the latest version of Home Assistant.

**Comment by h4de5** [comment]
there is a new release coming soon. but your issue is more likely related to a too big vimar installation. see #73 and #62 - if it is, there is no solution for this yet.
