### ISSUE TITLE
2024.10.0 Not update light status after action(turn on)

### ISSUE THREAD

**Issue by aukyle** [h4de5/home-assistant-vimar#84]
With the latest version (2024.10.0), if I turn on the light, it turns on, but after 1-2 seconds the state changes from on to off. But the light is still on.

**Comment by h4de5** [comment]
just tested. unfortunately a valid claim :(
all my testing previously included switching on and off a light .. So I guess those switches to cached_property had implications after all..

**Comment by h4de5** [comment]
fixed and tested again. should be working!

**Comment by aukyle** [comment]
yes, it works! Thanks!
